# -*- coding: utf-8 -*-

from . import res_partner
from . import res_company
from . import res_users
from . import res_country
from . import local_py_district
from . import res_city
from . import local_py_tipo_fiscal
from . import local_py_tipo_identificacion_fiscal
from . import local_py_imputacion_tributaria
from . import account_journal
from . import account_payment_term
from . import account_account
from . import account_move
from . import account_move_line
from . import account_move_marangatu
from . import local_py_plan_cuentas_report
from . import local_py_rubrica
from . import local_py_configuracion_localizacion
from . import local_py_libro_report
from . import stock_quant
from . import stock_move
from . import local_py_stock_valorizado_linea
from . import account_payment
from . import local_py_orden_pago_factura
from . import local_py_orden_pago_medio
from . import local_py_orden_pago
from . import local_py_chequera
from . import local_py_chequera_cheque
from . import local_py_numero_a_letras
from . import local_py_report_impresion_cheques
from . import local_py_no_retencion
from . import local_py_retencion_emitida
from . import local_py_retencion_recibida
from . import local_py_concepto_iva
from . import local_py_tesaka_import
from . import local_py_tesaka_import_linea
from . import local_py_concepto_renta_no_residente
from . import local_py_recibo_serie
from . import local_py_cheque_cliente
from . import local_py_recibo_factura
from . import local_py_recibo_medio
from . import local_py_recibo
