# -*- coding: utf-8 -*-
{
    "name": "Local_Py",
    "summary": """
        Localización para Paraguay: validación de RUT, campos Timbrado y
        Nro. Documento en diarios y facturas, Tipo Fiscal, Libro Ventas y Libro Compras,
        permisos contables automáticos y configuración de precios con impuestos incluidos""",
    "description": """
        Localización para Paraguay: validación de RUT, campos Timbrado y
        Nro. Documento en diarios y facturas, Tipo Fiscal, Libro Ventas y Libro Compras,
        permisos contables automáticos para productos, categorías, clientes y proveedores,
        y configuración de "Impuestos incluidos" en precios.

        El plan de cuentas, grupos de cuenta, impuestos predeterminados, moneda de
        compañía y país fiscal pasaron al módulo l10n_py (paquete nativo de
        Localización Fiscal Paraguay). Este módulo se encarga de todo lo que ese
        paquete no cubre.
    """,
    "author": "FC_Py",
    "website": "http://www.www.com.py",
    "category": "Localización",
    "version": "2026.13.003",
    "license": "LGPL-3",
    "depends": ["base", "account", "base_address_extended", "mail", "stock", "stock_account"],
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/account_groups_data.xml",
        "data/res.country.state.csv",
        "data/res.district.csv",
        "data/res.city.csv",
        "data/local_py_tipo_identificacion_fiscal_data.xml",
        "data/local_py_imputacion_tributaria_data.xml",
        "data/local_py_tipo_fiscal_data.xml",
        "data/local_py_orden_pago_sequence.xml",
        "views/res_partner_views.xml",
        "views/res_country_views.xml",
        "views/local_py_tipo_fiscal_views.xml",
        "views/local_py_district_views.xml",
        "views/res_city_views.xml",
        "views/local_py_tipo_identificacion_fiscal_views.xml",
        "views/local_py_imputacion_tributaria_views.xml",
        "views/local_py_rubrica_views.xml",
        "views/local_py_configuracion_localizacion_views.xml",
        "views/local_py_renumeracion_fiscal_wizard_views.xml",
        "views/local_py_limpiar_numeracion_wizard_views.xml",
        "views/local_py_asientos_fiscales_views.xml",
        "views/local_py_report_libro_diario.xml",
        "views/local_py_report_libro_mayor.xml",
        "views/local_py_libro_wizard_views.xml",
        "views/local_py_report_libro_inventario.xml",
        "views/local_py_libro_inventario_wizard_views.xml",
        "views/local_py_report_estado_resultado.xml",
        "views/local_py_estado_resultado_wizard_views.xml",
        "views/stock_quant_move_views.xml",
        "views/local_py_report_stock_valorizado.xml",
        "views/local_py_stock_valorizado_linea_views.xml",
        "views/local_py_stock_valorizado_wizard_views.xml",
        "views/account_journal_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_term_views.xml",
        "views/libro_ventas_wizard_views.xml",
        "views/libro_compras_wizard_views.xml",
        "views/libro_marangatu_views.xml",
        "views/config_paraguay_wizard_views.xml",
        "views/local_py_plan_cuentas_report_views.xml",
        "views/local_py_report_orden_pago.xml",
        "views/local_py_orden_pago_views.xml",
        "views/local_py_chequera_views.xml",
        "views/account_journal_chequera_views.xml",
        "views/local_py_orden_pago_deshacer_wizard_views.xml",
        "views/local_py_report_impresion_cheques.xml",
        "views/local_py_impresion_cheques_wizard_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "catalogo_tipo": "H",
    "catalogo_superior": "localizacion",
}
